import Head from 'next/head'
import Image from 'next/image'
import Form from '../components/Form'
import { AiOutlineMail } from 'react-icons/ai';
import { BsTwitter } from 'react-icons/bs';
import { FaFacebook, FaLinkedinIn } from 'react-icons/fa';
import signup from '../public/signup.png'
import logo from "../public/logo.png"


export default function Home() {
  return (
    <div>
      <Head>
        <title>Registration Section</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>


      <div id='contact' className='w-full lg:h-screen'>
      <div className='max-w-[1240px] m-auto px-2 py-16 w-full '>
        <div className='grid lg:grid-cols-5 gap-8'>
          {/* left */}
          <div className='col-span-3 lg:col-span-2 w-full h-full shadow-xl shadow-gray-400 rounded-xl p-4'>
            <div className='lg:p-4 h-auto '>
              <div>
                <Image
                  className='rounded-xl hover:scale-105 ease-in duration-300'
                  src={signup}
                  height={1220}
                  width={1220}
                  alt='/'
                />
              </div>
                <p>itzeazy is a Govtech startup founded in January 2015. Its one stop solution for Govt. documents. It has head quarter in New Delhi and services are available in 12 cities of India . In a short span of 4 years it has become no. 1 service provider in India for Govt.</p>
              <div>
                <p className='uppercase pt-8'>Connect With us</p>
                <div className='flex items-center justify-between py-4'>
                  <div className='rounded-full shadow-lg shadow-gray-400 p-6 cursor-pointer hover:scale-110 ease-in duration-300'>
                    <FaLinkedinIn />
                  </div>
                  <div className='rounded-full shadow-lg shadow-gray-400 p-6 cursor-pointer hover:scale-110 ease-in duration-300'>
                    <FaFacebook />
                  </div>
                  <div className='rounded-full shadow-lg shadow-gray-400 p-6 cursor-pointer hover:scale-110 ease-in duration-300'>
                    <AiOutlineMail />
                  </div>
                  <div className='rounded-full shadow-lg shadow-gray-400 p-6 cursor-pointer hover:scale-110 ease-in duration-300'>
                    <BsTwitter />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* right */}
          <div className='col-span-3 w-full h-auto shadow-xl shadow-gray-400 rounded-xl lg:p-4'>
               
            <div className='p-4'>
              <div className="text-center">
              <Image src={logo} width={100} height={100} alt="logo" />
              <h1 className="text-red-600 font-bold text-2xl">Let Get You Started</h1>
              </div>
             <Form />
            </div>
           
          </div>
        </div>
        </div>
          
        </div>
      </div>
  )
}
